pages:
  - Home: 'index.md'
  - Getting Started: 'getting_started.md'
  - Configuration: 'configuration.md'
  - Events: 'events.md'
  - Apex: 'apex.md'

site_name: Kerosene Documentation
repo_url: https://github.com/banctilrobitaille/kerosene-doc

markdown_extensions:
  - admonition
  - smarty
  - sane_lists

theme: readthedocs